language: node_js
node_js:
- lts/*
script:
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: ijBaW1kf0/5zObfww/hi9RzMlrQlcl+A/d9ei61Y3zXP0GPKvS1G8rXBNS5u1kPevct/6FSYobOUZQke7/o0OLDb6WPcPxVkze6MKVMOz3SljLGnyrivQzfOgmlywO+kYjXWX7unT4BgDomefWOABOv3vnev1YSDDAEzRfs6TuagbzFCcQtEAt0bs05U0bfyb9KlKKy1sCsGy1r/sGzW4RyQ/pq7sPIyX02qnwWHH3elQkUS3yLb4qT13i+0aJQkHwCJ2nAC6tSwfI+zkpCoPwq7rv19LlKRNl+fe9Du/oATTx7x3t0gPwT0WJyisGcN1qrg34giBEriNIOcJwWOZeusHvpCGAyIlP1PjNi/OeEKHoiAY4FWlfgTKyF+p3Y3kH5sLXJ2dMoEaPBcOau9poQsIFG4yg9LCiUVjlwDjHivQ9MBV/IZD9VXDlW7OXHUfnOzSHBXnygUpFyoDl4Lb7yPOLZl3wTQGy6mbUMg7nmIHaB9rTx7zo/F/BYlMmmOvSMVHhBFk0BlrB4ZMW1ou/AXZFS3vDvm34anJLtFD0ZSjqtj8M3DCEYYr6QaBF9f/i3y86QGsjBuIYiTeOzqlnSZuUqPo3BZCVWkJPnselnsde3f+9eowpzWW+SQ+6t1OzNBbyx/C9AY1WP9pib5T43d00WKTpvPicRZEEQVTks=
  strategy: git
