language: node_js
node_js:
- lts/*
script:
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: gDXBZSBABMwRjCmAfr0ApuUyi/am+nFtvMuU10Pm7EXQzkInv51qGijfCYGD6fxM6A1g0r5futcK2or2E/1ilFhg5sAzbvAuD4OtWV/6BNcAniIiEIjYnRAXKqHSRfbHVnnjwxGC71uVyiILy7cLGWmhjkDc4/Ri82AOc6ykfezEpt+R9l4izpxC5ZGdr/lbf9dtvzEQ+Aow+QdEZ2cYq1FjOnbJvRSWM2v0G2C0J8cgjzFcz6ENU/hLwIRhlLPoyKhGdNATF799ecsyC+49XM3jVr0/YHKn1VDPSQPNavPKkDJbH0qee0q9sLT3eSrvpkftkPy1/8tykBcmX+d9ka+i3QQVRdRYCScOb+Ff9kJAUp8fHrfKccCNkIx3iHYuO+zJsx4OK446ByVF2LexH5wPr7ZrC2K4DEc/MFtuYSerWgOdkiI885nLRnEgibFMymXf0uJBj+wXxJSQDzrPM34BLetYjY+8hawPVlUWhk15/v3h/u8Hx3lPdFO8Rlz/jUaW9b3jxFwInrPjWfEKYqlHgeaHq0vaGmBLnxEo7RmHdY5lugEVQu+n43QRfZsSYTSBE9d0ECzFHWU26HzosFVwMV9ysVY5ZJoTNZeShpwjF6N9V2kI5zL5OXROkJRXT2Po8bxXqPxp6WWabn7oN9cWPOjUdd/eiAVxEVMJuiI=
  strategy: git
