language: node_js
node_js:
  - lts/*
script:
- npm run lint
deploy:
  provider: heroku
  api_key: qY6i9kfg/tsOvNqGOz8Zr6bh9Pm9K0UPxuivIE913k8bQEmIODgfEI4d1oVv0NNH/mPkO6qNaJ74ZDfLQzQZAtzo4jYCGz+XbGsP7phXUoPSC2yluzGKfYaD80q+IxI9baFWDB3lA1AZV2SYLxiZrdJ8DarfQV7N+Pyhm/d+Vwe2a/Fn2ZL3b96M/Vi1JXeUs45wXFR8KIGKVh3xqG1pKmgoYb0Ul9seYDUlTkkA3Tiie7GNFZkc2DRHlj5hqSDZBnFxf/jGvhGKaQ12MqFL7+lEBwvKgTl9zx7lm1Ff8/hKYKC+qwA7JXBA/4COc2FPH+gKMdR63/ZA1Fwu3uIjxOqXaUl4DOE+bq0E/HX0Cwy2bmwjz4Y7haOkJzHKZIxSiCxaM9gdFXJ1AZKU3HSJ4C/bazjz1cAgjK/mw6MnXxBfTdWN+6NFjLZN1krLUKRvWV0ZRjYSHV1AGkAczjyDSGp78nXEHeOqHK7tdGGvYaerHSDoU8sQVRMdUq/lMkcNo0twUUEm32a9oyvCflyV53bwmcdfKdMSFuyz6kHS+uP63/Gs7T5/qzYST4Jeg853jn1ooLMwa0CCRoh+wN7h6xC96F6/27x5HwsD7Bnp6Ot/Gs+MNJ400CMCIDdVQR8Vu1swyQ7ZFz3cyZRjoxoZRtbBjdA2Yaziy3EcVx5rjCk=
  strategy: git
