language: node_js
node_js:
  - lts/*
script:
- npm run lint
deploy:
  provider: heroku
  api_key: J6mmLozVTXLod/MRHWIkCebV34jJkJqN4xkAHMeTgDLr9/UH9MW/tIeXtKKBdBwffq7xjMMM2vKWgxT40QAf8Wf4V1sn/HedEI648n6/BAUNz/1lAgdBkO01XlcV5d8H/pkdZ7/r22vlEbELn0twy2110o3RchpEivK8N0l6WTARdxJtZ3dh0qDhQY+Lgn4KgLOUlRdBtfETq/DNo6bHM1f7Fbifywv7bt/nIyyh4MeHiRW89SsQwE+hzYQJvxSJ3o3XHsUOhAGbqSl15FAPEC7UgDawkI26XXp6Ie4EzrMLQaiBxA3kMooCSLDlABp7HX4PCWxf6kbwHpNHZ/KIa0xyryfxA6xosxFJ8LZSODl9KHbCVBmd/jB1zQx9mBMG3Lbo0Mj20uyuDEWdbqpb21kDnOQYdF66fJbsuittmckBssmq6aI4QSiTOgEup5OWKbALd88502egDmDoGQoJXSDD7B9ETnTGDV5MUDoCh8Q4uLH2IHmCJb3rjC79H3zYzEqaYTH6QPnzi6gNUKybSPg9EPtCqtv6efxyUciU6356VED3yynoHQN40Yx1TQROaNFk6e00EeZJCFZmdFjDHjabWFJBH9UYhyYfDlOMbBPVA5L0H4npnFbsu+FrWgnyjMTLkt0aZD6zvHdd4lUXhq2Duyyu5vR5VZDSR9WEY9w=
  strategy: git
