language: node_js
node_js:
- lts/*
script:
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: bsj+VTHoOCwJEo/nLCmFAivC9FXAoHncbyWxVLvherC1DHntxzVcfeqKCeAuBamsEJQq7A8bCS1OjJKjamn6SqL+CR8O0DSUh1mPwzlHjWSWzRsKEaWULHtJlM2PnTaxKpLoPKfVg9ht6ZLiFJQNj0bQcXNWGqhZc7v1Uc/oo1vvrqoTK9upYUVNRKAhRr8937KpmCa5dQ7anSRPVLyeRYrbFGdVYqvYHewEPANkjIyfB12vp643DEn7Uuq8jFbSnoHcGaO3TVihLqjdibvuJtOpwDc0LUuzFtV+1IRPTpNVzgbAYHwrNe8H0JTGxuV/VAA4L/aMlqKkiWyhohs0nKbYMpXRkg0I9p7X4ajeTarHOSvXnzfM0j843GmsO1I/yfa0836BhyOkq01+n40fHytE831zVo8NRTVD30RilhdQoboJ9WnvWcj5fxjO0FDMrDgmrb0mJXqVNOvIqRtTv5XqcQQBdWjiZS7Z00bwmJD+8R+pMV9mHokoNFE3YE2BYeHZ4NRPixextxFno7nd/Cc3Qc3fGLz0m348dIKd2xWKTT2GZJYBHiGFlbPo6Shlq/HKwvA9hx3IHDK/bBH5FvCZwlOjb6ZSZT7alTVMKiCX9v9xGQML3QDJ4jDTCqR6x+mYwv8nJl2knK660kpMjbT9owQtpjZ/B5ggSMo1mSY=
  on:
    branch: master
  strategy: git
